# Generated by Django 3.2.15 on 2025-08-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20250825_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='phone')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('level', models.SmallIntegerField(choices=[(1, '1 level'), (2, '2 level'), (3, '3 level'), (4, '4 level')], default=1, verbose_name='level')),
                ('status', models.SmallIntegerField(choices=[(1, 'use'), (2, 'unused')], default=2, verbose_name='status')),
            ],
        ),
    ]
