# Generated by Django 3.2.15 on 2025-08-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'urgent'), (2, 'normal'), (3, 'temporary')], default=1, verbose_name='level')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('details', models.TextField(max_length=64, verbose_name='details')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='assignee')),
            ],
        ),
    ]
