# Generated by Django 3.2.15 on 2025-08-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='oid')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.SmallIntegerField(choices=[(1, 'paid'), (2, 'unpaid')], default=1, verbose_name='status')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='admin')),
            ],
        ),
    ]
