# Generated by Django 3.2.15 on 2025-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Employee Name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('img', models.CharField(max_length=128, verbose_name='img')),
            ],
        ),
    ]
