# Generated by Django 3.2.15 on 2025-08-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='img',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='age',
            new_name='population',
        ),
    ]
